/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataBase;

import static DataBase.FillComplaint.matricholder;

/**
 *
 * @author Mowumi
 */
public class Appointment extends javax.swing.JFrame {

    /**
     * Creates new form Appointment
     */
    public Appointment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newap_button = new javax.swing.JButton();
        upcominap_button = new javax.swing.JButton();
        pastap_button = new javax.swing.JButton();
        goto_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mathol_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Events/Appointment Dashboard");

        newap_button.setText("New Appointment");
        newap_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newap_buttonActionPerformed(evt);
            }
        });

        upcominap_button.setText("Upcoming Appointments");
        upcominap_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upcominap_buttonActionPerformed(evt);
            }
        });

        pastap_button.setText("Past Appointments");
        pastap_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastap_buttonActionPerformed(evt);
            }
        });

        goto_button.setText("Go to student dashboard");
        goto_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goto_buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Matric Number:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mathol_label, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(goto_button)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newap_button)
                        .addGap(24, 24, 24)
                        .addComponent(upcominap_button)
                        .addGap(18, 30, Short.MAX_VALUE)
                        .addComponent(pastap_button)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(goto_button)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mathol_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newap_button, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upcominap_button, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pastap_button, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newap_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newap_buttonActionPerformed
        this.hide();
        NewAppointment NP = new NewAppointment();
        NP.setVisible(true);
    }//GEN-LAST:event_newap_buttonActionPerformed

    private void goto_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goto_buttonActionPerformed
        this.dispose();
        student stu = new student();
        stu.label.setText(mathol_label.getText());
        stu.setVisible(true);
    }//GEN-LAST:event_goto_buttonActionPerformed

    private void upcominap_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upcominap_buttonActionPerformed
        this.dispose();
        UpcomingAppointment up = new UpcomingAppointment();
        mathol_label.setText(student.label.getText());
        up.setVisible(true);
    }//GEN-LAST:event_upcominap_buttonActionPerformed

    private void pastap_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastap_buttonActionPerformed
        this.dispose();
        PastAppointment pp = new PastAppointment();
        mathol_label.setText(student.label.getText());
        pp.setVisible(true);
    }//GEN-LAST:event_pastap_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Appointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goto_button;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel mathol_label;
    private javax.swing.JButton newap_button;
    private javax.swing.JButton pastap_button;
    private javax.swing.JButton upcominap_button;
    // End of variables declaration//GEN-END:variables
}
